// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.Infrastructure;

#nullable disable

namespace MovieApp.Infrastructure.Migrations
{
    [DbContext(typeof(MovieAppDbContext))]
    [Migration("20260511203853_AddBadgeDescription")]
    partial class AddBadgeDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarathonMovie", b =>
                {
                    b.Property<int>("MarathonId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("MarathonId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("MarathonMovies", (string)null);
                });

            modelBuilder.Entity("MovieActors", b =>
                {
                    b.Property<int>("ActorsId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("ActorsId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            ActorsId = 3,
                            MovieId = 3
                        },
                        new
                        {
                            ActorsId = 3,
                            MovieId = 6
                        },
                        new
                        {
                            ActorsId = 1,
                            MovieId = 7
                        },
                        new
                        {
                            ActorsId = 2,
                            MovieId = 8
                        },
                        new
                        {
                            ActorsId = 4,
                            MovieId = 11
                        });
                });

            modelBuilder.Entity("MovieApp.Core.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tom Cruise"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Scarlett Johansson"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Leonardo DiCaprio"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Emma Watson"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dwayne Johnson"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Jennifer Lawrence"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tom Hanks"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Angelina Jolie"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Chris Evans"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Natalie Portman"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Johnny Depp"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Meryl Streep"
                        });
                });

            modelBuilder.Entity("MovieApp.Core.Models.AmbassadorProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("PermanentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RewardBalance")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("PermanentCode")
                        .IsUnique();

                    b.ToTable("AmbassadorProfiles");
                });

            modelBuilder.Entity("MovieApp.Core.Models.Badge", b =>
                {
                    b.Property<int>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BadgeId"));

                    b.Property<int>("CriteriaValue")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BadgeId");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            BadgeId = 1,
                            CriteriaValue = 10,
                            Description = "Reach 10 profile progress points.",
                            Name = "Film Fanatic"
                        },
                        new
                        {
                            BadgeId = 2,
                            CriteriaValue = 5,
                            Description = "Reach 5 profile progress points.",
                            Name = "Reviewer"
                        },
                        new
                        {
                            BadgeId = 3,
                            CriteriaValue = 20,
                            Description = "Reach 20 profile progress points.",
                            Name = "Social Butterfly"
                        },
                        new
                        {
                            BadgeId = 4,
                            CriteriaValue = 1,
                            Description = "Reach 1 profile progress point.",
                            Name = "Early Bird"
                        },
                        new
                        {
                            BadgeId = 5,
                            CriteriaValue = 50,
                            Description = "Reach 50 profile progress points.",
                            Name = "Movie Buff"
                        },
                        new
                        {
                            BadgeId = 6,
                            CriteriaValue = 100,
                            Description = "Reach 100 profile progress points.",
                            Name = "Elite Member"
                        });
                });

            modelBuilder.Entity("MovieApp.Core.Models.Battle", b =>
                {
                    b.Property<int>("BattleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BattleId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FirstMovieId")
                        .HasColumnType("int");

                    b.Property<double>("InitialRatingFirstMovie")
                        .HasColumnType("float");

                    b.Property<double>("InitialRatingSecondMovie")
                        .HasColumnType("float");

                    b.Property<int?>("SecondMovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BattleId");

                    b.HasIndex("FirstMovieId");

                    b.HasIndex("SecondMovieId");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("MovieApp.Core.Models.Bet", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("BattleId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "BattleId");

                    b.HasIndex("BattleId");

                    b.HasIndex("MovieId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("MovieApp.Core.Models.Comment", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("MovieId");

                    b.HasIndex("ParentCommentId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            AuthorId = 2,
                            Content = "I can't wait for the sequel!",
                            CreatedAt = new DateTime(2026, 5, 11, 15, 38, 52, 100, DateTimeKind.Utc).AddTicks(2324),
                            MovieId = 1
                        },
                        new
                        {
                            MessageId = 2,
                            AuthorId = 3,
                            Content = "Agreed, the ending was insane.",
                            CreatedAt = new DateTime(2026, 5, 11, 18, 38, 52, 100, DateTimeKind.Utc).AddTicks(2330),
                            MovieId = 1,
                            ParentCommentId = 1
                        });
                });

            modelBuilder.Entity("MovieApp.Core.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Martin Scorsese"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ridley Scott"
                        },
                        new
                        {
                            Id = 6,
                            Name = "James Cameron"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Spike Lee"
                        },
                        new
                        {
                            Id = 8,
                            Name = "David Fincher"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Denis Villeneuve"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Wes Anderson"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ari Aster"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Paul Thomas Anderson"
                        });
                });

            modelBuilder.Entity("MovieApp.Core.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentEnrollment")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("HistoricalRating")
                        .HasColumnType("float");

                    b.Property<bool>("IsJoined")
                        .HasColumnType("bit");

                    b.Property<string>("LocationReference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TicketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatorUserId = 1,
                            CurrentEnrollment = 45,
                            Description = "Special screening of the Palme d'Or winner.",
                            DiscountPercentage = 0,
                            EventDateTime = new DateTime(2026, 5, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Premiere",
                            HistoricalRating = 4.7999999999999998,
                            IsJoined = false,
                            LocationReference = "Cinema Hall A",
                            MaxCapacity = 100,
                            PosterUrl = "",
                            TicketPrice = 25.00m,
                            Title = "Cannes Winner Screening"
                        },
                        new
                        {
                            Id = 2,
                            CreatorUserId = 1,
                            CurrentEnrollment = 10,
                            Description = "Back-to-back classics from the 50s.",
                            DiscountPercentage = 0,
                            EventDateTime = new DateTime(2026, 5, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Marathon",
                            HistoricalRating = 4.5,
                            IsJoined = false,
                            LocationReference = "Retro Cinema",
                            MaxCapacity = 50,
                            PosterUrl = "",
                            TicketPrice = 40.00m,
                            Title = "Vintage Film Marathon"
                        },
                        new
                        {
                            Id = 3,
                            CreatorUserId = 1,
                            CurrentEnrollment = 150,
                            Description = "Watch the latest sci-fi hit followed by a talk.",
                            DiscountPercentage = 0,
                            EventDateTime = new DateTime(2026, 5, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            EventType = "Special",
                            HistoricalRating = 4.9000000000000004,
                            IsJoined = false,
                            LocationReference = "Tech Hub Theater",
                            MaxCapacity = 200,
                            PosterUrl = "",
                            TicketPrice = 15.00m,
                            Title = "Director's Q&A: Sci-Fi Night"
                        });
                });

            modelBuilder.Entity("MovieApp.Core.Models.FavoriteEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteEvents");
                });

            modelBuilder.Entity("MovieApp.Core.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Mystery"
                        });
                });

            modelBuilder.Entity("MovieApp.Core.Models.Marathon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastFeaturedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrerequisiteMarathonId")
                        .HasColumnType("int");

                    b.Property<string>("Theme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WeekScoping")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Marathons");
                });

            modelBuilder.Entity("MovieApp.Core.Models.MarathonProgress", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("MarathonId")
                        .HasColumnType("int");

                    b.Property<int>("CompletedMoviesCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("TriviaAccuracy")
                        .HasColumnType("float");

                    b.HasKey("UserId", "MarathonId");

                    b.HasIndex("MarathonId");

                    b.ToTable("MarathonProgressions");
                });

            modelBuilder.Entity("MovieApp.Core.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 3.7999999999999998,
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            DurationMinutes = 0,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/20f2GThu22hp5MgCA4dg3bZ3gTS.jpg",
                            ReleaseYear = 1994,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 0.0,
                            Description = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            DurationMinutes = 0,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                            ReleaseYear = 2008,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 0.0,
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
                            DurationMinutes = 0,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg",
                            ReleaseYear = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 4,
                            AverageRating = 0.0,
                            Description = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            DurationMinutes = 0,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
                            ReleaseYear = 1994,
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 5,
                            AverageRating = 5.0,
                            Description = "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
                            DurationMinutes = 0,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/kyeqWdyUXW608qlYkRqosgbbJyK.jpg",
                            ReleaseYear = 2009,
                            Title = "Avatar"
                        },
                        new
                        {
                            Id = 6,
                            AverageRating = 0.0,
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            DurationMinutes = 0,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg",
                            ReleaseYear = 2014,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 7,
                            AverageRating = 0.0,
                            Description = "Ethan Hunt and his IMF team, along with some familiar allies, race against time after a mission goes wrong.",
                            DurationMinutes = 0,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
                            ReleaseYear = 2018,
                            Title = "Mission: Impossible - Fallout"
                        },
                        new
                        {
                            Id = 8,
                            AverageRating = 4.7999999999999998,
                            Description = "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
                            DurationMinutes = 0,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
                            ReleaseYear = 2018,
                            Title = "Avengers: Infinity War"
                        },
                        new
                        {
                            Id = 9,
                            AverageRating = 0.0,
                            Description = "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
                            DurationMinutes = 0,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/kW9LmvYHAaS9iA0tHmZVq8hQYoq.jpg",
                            ReleaseYear = 2013,
                            Title = "The Wolf of Wall Street"
                        },
                        new
                        {
                            Id = 10,
                            AverageRating = 4.7000000000000002,
                            Description = "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
                            DurationMinutes = 0,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
                            ReleaseYear = 2017,
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            Id = 11,
                            AverageRating = 0.0,
                            Description = "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
                            DurationMinutes = 0,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/Cw4hIUIAmSYfK9QfaUW5igp9La.jpg",
                            ReleaseYear = 1994,
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 12,
                            AverageRating = 0.0,
                            Description = "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
                            DurationMinutes = 0,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/wN2xWp1eIwCKOD0BHTcErTBv1Uq.jpg",
                            ReleaseYear = 2000,
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 13,
                            AverageRating = 0.0,
                            Description = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
                            DurationMinutes = 0,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg",
                            ReleaseYear = 1999,
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 14,
                            AverageRating = 4.9000000000000004,
                            Description = "Allied soldiers from Belgium, the British Empire and France are surrounded by the German Army, and evacuated during a fierce battle in World War II.",
                            DurationMinutes = 0,
                            PosterUrl = "https://image.tmdb.org/t/p/w500/ebSnODDg9lbsMIaWg2uAbjn7TO5.jpg",
                            ReleaseYear = 2017,
                            Title = "Dunkirk"
                        });
                });

            modelBuilder.Entity("MovieApp.Core.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MovieApp.Core.Models.ReferralLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmbassadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("ReferredUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AmbassadorId");

                    b.HasIndex("EventId");

                    b.HasIndex("ReferredUserId");

                    b.ToTable("ReferralLogs");
                });

            modelBuilder.Entity("MovieApp.Core.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("ActingRating")
                        .HasColumnType("int");

                    b.Property<string>("ActingText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CgiRating")
                        .HasColumnType("int");

                    b.Property<string>("CgiText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("CinematographyRating")
                        .HasColumnType("int");

                    b.Property<string>("CinematographyText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExtraReview")
                        .HasColumnType("bit");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("PlotRating")
                        .HasColumnType("int");

                    b.Property<string>("PlotText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SoundRating")
                        .HasColumnType("int");

                    b.Property<string>("SoundText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<float>("StarRating")
                        .HasColumnType("real");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            ActingRating = 5,
                            CgiRating = 4,
                            CinematographyRating = 5,
                            Content = "A masterpiece of modern cinema.",
                            CreatedAt = new DateTime(2026, 5, 11, 20, 38, 52, 118, DateTimeKind.Utc).AddTicks(8291),
                            IsExtraReview = true,
                            MovieId = 1,
                            PlotRating = 5,
                            SoundRating = 5,
                            StarRating = 4.5f,
                            UserId = 2
                        },
                        new
                        {
                            ReviewId = 2,
                            ActingRating = 0,
                            CgiRating = 0,
                            CinematographyRating = 0,
                            Content = "Decent, but could be better.",
                            CreatedAt = new DateTime(2026, 5, 11, 20, 38, 52, 118, DateTimeKind.Utc).AddTicks(8294),
                            IsExtraReview = false,
                            MovieId = 1,
                            PlotRating = 0,
                            SoundRating = 0,
                            StarRating = 3f,
                            UserId = 3
                        },
                        new
                        {
                            ReviewId = 3,
                            ActingRating = 0,
                            CgiRating = 0,
                            CinematographyRating = 0,
                            Content = "Visually stunning and immersive.",
                            CreatedAt = new DateTime(2026, 5, 11, 20, 38, 52, 118, DateTimeKind.Utc).AddTicks(8295),
                            IsExtraReview = false,
                            MovieId = 5,
                            PlotRating = 0,
                            SoundRating = 0,
                            StarRating = 5f,
                            UserId = 2
                        },
                        new
                        {
                            ReviewId = 4,
                            ActingRating = 0,
                            CgiRating = 0,
                            CinematographyRating = 0,
                            Content = "The ultimate Marvel event.",
                            CreatedAt = new DateTime(2026, 5, 11, 20, 38, 52, 118, DateTimeKind.Utc).AddTicks(8296),
                            IsExtraReview = false,
                            MovieId = 8,
                            PlotRating = 0,
                            SoundRating = 0,
                            StarRating = 4.8f,
                            UserId = 3
                        },
                        new
                        {
                            ReviewId = 5,
                            ActingRating = 0,
                            CgiRating = 0,
                            CinematographyRating = 0,
                            Content = "A perfect sequel to a classic.",
                            CreatedAt = new DateTime(2026, 5, 11, 20, 38, 52, 118, DateTimeKind.Utc).AddTicks(8297),
                            IsExtraReview = false,
                            MovieId = 10,
                            PlotRating = 0,
                            SoundRating = 0,
                            StarRating = 4.7f,
                            UserId = 2
                        },
                        new
                        {
                            ReviewId = 6,
                            ActingRating = 0,
                            CgiRating = 0,
                            CinematographyRating = 0,
                            Content = "Nolan's best work yet.",
                            CreatedAt = new DateTime(2026, 5, 11, 20, 38, 52, 118, DateTimeKind.Utc).AddTicks(8297),
                            IsExtraReview = false,
                            MovieId = 14,
                            PlotRating = 0,
                            SoundRating = 0,
                            StarRating = 4.9f,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("MovieApp.Core.Models.Reward", b =>
                {
                    b.Property<int>("RewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RewardId"));

                    b.Property<string>("ApplicabilityScope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountValue")
                        .HasColumnType("float");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<bool>("RedemptionStatus")
                        .HasColumnType("bit");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RewardId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Rewards");
                });

            modelBuilder.Entity("MovieApp.Core.Models.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScreeningTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("MovieId");

                    b.ToTable("Screenings");
                });

            modelBuilder.Entity("MovieApp.Core.Models.SeatBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Column")
                        .HasColumnType("int");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SeatBookings");
                });

            modelBuilder.Entity("MovieApp.Core.Models.TriviaQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TriviaQuestions");
                });

            modelBuilder.Entity("MovieApp.Core.Models.TriviaReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRedeemed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TriviaRewards");
                });

            modelBuilder.Entity("MovieApp.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AuthSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuthProvider", "AuthSubject")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthProvider = "local",
                            AuthSubject = "admin",
                            Username = "AdminUser"
                        },
                        new
                        {
                            Id = 2,
                            AuthProvider = "local",
                            AuthSubject = "beta",
                            Username = "UserBeta"
                        },
                        new
                        {
                            Id = 3,
                            AuthProvider = "local",
                            AuthSubject = "gamma",
                            Username = "UserGamma"
                        });
                });

            modelBuilder.Entity("MovieApp.Core.Models.UserBadge", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("MovieApp.Core.Models.UserEventAttendance", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("UserEventAttendances");
                });

            modelBuilder.Entity("MovieApp.Core.Models.UserSpinData", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("BonusSpins")
                        .HasColumnType("int");

                    b.Property<int>("DailySpinsRemaining")
                        .HasColumnType("int");

                    b.Property<int>("EventSpinRewardsToday")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSlotSpinReset")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastTriviaSpinReset")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoginStreak")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserSpinStates");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BonusSpins = 2,
                            DailySpinsRemaining = 5,
                            EventSpinRewardsToday = 0,
                            LastLoginDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSlotSpinReset = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTriviaSpinReset = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoginStreak = 1
                        },
                        new
                        {
                            UserId = 2,
                            BonusSpins = 1,
                            DailySpinsRemaining = 3,
                            EventSpinRewardsToday = 0,
                            LastLoginDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSlotSpinReset = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTriviaSpinReset = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoginStreak = 0
                        },
                        new
                        {
                            UserId = 3,
                            BonusSpins = 0,
                            DailySpinsRemaining = 1,
                            EventSpinRewardsToday = 0,
                            LastLoginDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastSlotSpinReset = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastTriviaSpinReset = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoginStreak = 0
                        });
                });

            modelBuilder.Entity("MovieApp.Core.Models.UserStats", b =>
                {
                    b.Property<int>("StatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatsId"));

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WeeklyScore")
                        .HasColumnType("int");

                    b.HasKey("StatsId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("UserStats");

                    b.HasData(
                        new
                        {
                            StatsId = 1,
                            TotalPoints = 1500,
                            UserId = 1,
                            WeeklyScore = 200
                        },
                        new
                        {
                            StatsId = 2,
                            TotalPoints = 450,
                            UserId = 2,
                            WeeklyScore = 50
                        },
                        new
                        {
                            StatsId = 3,
                            TotalPoints = 100,
                            UserId = 3,
                            WeeklyScore = 10
                        });
                });

            modelBuilder.Entity("MovieApp.Core.Models.WatchedEvent", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EventId");

                    b.ToTable("WatchedEvents");
                });

            modelBuilder.Entity("MovieDirectors", b =>
                {
                    b.Property<int>("DirectorsId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("DirectorsId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieDirectors");

                    b.HasData(
                        new
                        {
                            DirectorsId = 2,
                            MovieId = 2
                        },
                        new
                        {
                            DirectorsId = 2,
                            MovieId = 3
                        },
                        new
                        {
                            DirectorsId = 2,
                            MovieId = 6
                        },
                        new
                        {
                            DirectorsId = 2,
                            MovieId = 14
                        },
                        new
                        {
                            DirectorsId = 3,
                            MovieId = 9
                        },
                        new
                        {
                            DirectorsId = 4,
                            MovieId = 4
                        });
                });

            modelBuilder.Entity("MovieGenres", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("GenresId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieGenres");

                    b.HasData(
                        new
                        {
                            GenresId = 3,
                            MovieId = 1
                        },
                        new
                        {
                            GenresId = 1,
                            MovieId = 2
                        },
                        new
                        {
                            GenresId = 7,
                            MovieId = 2
                        },
                        new
                        {
                            GenresId = 6,
                            MovieId = 3
                        },
                        new
                        {
                            GenresId = 7,
                            MovieId = 4
                        },
                        new
                        {
                            GenresId = 1,
                            MovieId = 5
                        },
                        new
                        {
                            GenresId = 6,
                            MovieId = 5
                        },
                        new
                        {
                            GenresId = 6,
                            MovieId = 6
                        },
                        new
                        {
                            GenresId = 1,
                            MovieId = 7
                        },
                        new
                        {
                            GenresId = 1,
                            MovieId = 8
                        },
                        new
                        {
                            GenresId = 3,
                            MovieId = 9
                        },
                        new
                        {
                            GenresId = 6,
                            MovieId = 10
                        },
                        new
                        {
                            GenresId = 3,
                            MovieId = 11
                        },
                        new
                        {
                            GenresId = 1,
                            MovieId = 12
                        },
                        new
                        {
                            GenresId = 3,
                            MovieId = 12
                        },
                        new
                        {
                            GenresId = 6,
                            MovieId = 13
                        },
                        new
                        {
                            GenresId = 3,
                            MovieId = 14
                        });
                });

            modelBuilder.Entity("MarathonMovie", b =>
                {
                    b.HasOne("MovieApp.Core.Models.Marathon", null)
                        .WithMany()
                        .HasForeignKey("MarathonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Core.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieActors", b =>
                {
                    b.HasOne("MovieApp.Core.Models.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Core.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApp.Core.Models.AmbassadorProfile", b =>
                {
                    b.HasOne("MovieApp.Core.Models.User", null)
                        .WithOne()
                        .HasForeignKey("MovieApp.Core.Models.AmbassadorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApp.Core.Models.Battle", b =>
                {
                    b.HasOne("MovieApp.Core.Models.Movie", "FirstMovie")
                        .WithMany()
                        .HasForeignKey("FirstMovieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MovieApp.Core.Models.Movie", "SecondMovie")
                        .WithMany()
                        .HasForeignKey("SecondMovieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FirstMovie");

                    b.Navigation("SecondMovie");
                });

            modelBuilder.Entity("MovieApp.Core.Models.Bet", b =>
                {
                    b.HasOne("MovieApp.Core.Models.Battle", "Battle")
                        .WithMany("Bets")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Core.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MovieApp.Core.Models.User", "User")
                        .WithMany("Bets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battle");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Core.Models.Comment", b =>
                {
                    b.HasOne("MovieApp.Core.Models.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Core.Models.Movie", "Movie")
                        .WithMany("Comments")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Core.Models.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");

                    b.Navigation("Movie");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("MovieApp.Core.Models.Event", b =>
                {
                    b.HasOne("MovieApp.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApp.Core.Models.FavoriteEvent", b =>
                {
                    b.HasOne("MovieApp.Core.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApp.Core.Models.MarathonProgress", b =>
                {
                    b.HasOne("MovieApp.Core.Models.Marathon", null)
                        .WithMany()
                        .HasForeignKey("MarathonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Core.Models.Notification", b =>
                {
                    b.HasOne("MovieApp.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApp.Core.Models.ReferralLog", b =>
                {
                    b.HasOne("MovieApp.Core.Models.User", "Ambassador")
                        .WithMany()
                        .HasForeignKey("AmbassadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieApp.Core.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Core.Models.User", "ReferredUser")
                        .WithMany()
                        .HasForeignKey("ReferredUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ambassador");

                    b.Navigation("Event");

                    b.Navigation("ReferredUser");
                });

            modelBuilder.Entity("MovieApp.Core.Models.Review", b =>
                {
                    b.HasOne("MovieApp.Core.Models.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MovieApp.Core.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Core.Models.Reward", b =>
                {
                    b.HasOne("MovieApp.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApp.Core.Models.Screening", b =>
                {
                    b.HasOne("MovieApp.Core.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Core.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApp.Core.Models.TriviaReward", b =>
                {
                    b.HasOne("MovieApp.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApp.Core.Models.UserBadge", b =>
                {
                    b.HasOne("MovieApp.Core.Models.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Core.Models.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Core.Models.UserEventAttendance", b =>
                {
                    b.HasOne("MovieApp.Core.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.Core.Models.UserSpinData", b =>
                {
                    b.HasOne("MovieApp.Core.Models.User", null)
                        .WithOne()
                        .HasForeignKey("MovieApp.Core.Models.UserSpinData", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApp.Core.Models.UserStats", b =>
                {
                    b.HasOne("MovieApp.Core.Models.User", "User")
                        .WithOne("UserStats")
                        .HasForeignKey("MovieApp.Core.Models.UserStats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieDirectors", b =>
                {
                    b.HasOne("MovieApp.Core.Models.Director", null)
                        .WithMany()
                        .HasForeignKey("DirectorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Core.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieGenres", b =>
                {
                    b.HasOne("MovieApp.Core.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApp.Core.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApp.Core.Models.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("MovieApp.Core.Models.Battle", b =>
                {
                    b.Navigation("Bets");
                });

            modelBuilder.Entity("MovieApp.Core.Models.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("MovieApp.Core.Models.Movie", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MovieApp.Core.Models.User", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("Comments");

                    b.Navigation("Reviews");

                    b.Navigation("UserBadges");

                    b.Navigation("UserStats");
                });
#pragma warning restore 612, 618
        }
    }
}
